package nz.ac.vuw.ecs.swen225.gp21.persistency;

import nz.ac.vuw.ecs.swen225.gp21.domain.*;
import nz.ac.vuw.ecs.swen225.gp21.persistency.levels.level2.Actor;
import org.jdom2.Attribute;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;



public class LoadLevel {
    private static final String saveFile = "Saves";
    private static final String levelFile = "levels";
    static int mapSize;
    private final String LEVEL1INFO = "Grab all the correct keys to open the doors in order to get the treasures to open the exit lock!";

    /**
     * Load a level file (xml)
     * @param fileName file to be loaded
     * @return 2d tile array that represents the board for game logic
     */
    public Tile[][] loadLevel(String fileName){
        Map<Point, String> points = makeMap(fileName, false);
        Tile[][] tiles = makeTiles(points);
        return tiles;

    }

    /**
     * Load a save file (xml)
     * @param saveName file to be loaded
     * @return 2d tile array that represents the board for game logic
     */
    public Tile[][] loadSave(String saveName){
        Map<Point, String> points = makeMap(saveName, true);
        Tile[][] tiles = makeTiles(points);
        return tiles;

    }

    /**
     * Makes a map of Point to String. Each entry pair is a tile represented by a string and its location is contained within the point
     * @param file File to be loaded
     * @param isSave true if is a save file, false if a levelFile
     * @return Generated map of Point to string
     */
    public Map<Point, String> makeMap(String file, boolean isSave){
        String folder;
        if(isSave){
            folder = saveFile;
        }else{
            folder = levelFile;
        }
        String fileName = System.getProperty("user.dir") + "/src//nz/ac/vuw/ecs/swen225/gp21/persistency/" + folder + "/" + file;
        File inputFile = new File(fileName);
        SAXBuilder saxBuilder = new SAXBuilder();

        Map<Point, String> cells = new HashMap<>();

        try {
            Document document = saxBuilder.build(inputFile); //create the Document from the input file
            Element classElement = document.getRootElement();
            Attribute attribute =  classElement.getAttribute("size");
            mapSize = attribute.getIntValue();

            List<Element> cellList = classElement.getChildren(); //construct list of all cel

            for(int i = 0; i < cellList.size(); i++){
                char colorChar;
                Element cell = cellList.get(i);
                int x = Integer.parseInt((cell.getChildText("x")).trim());
                int y = Integer.parseInt((cell.getChildText("y")).trim());
                String type = cell.getChildText("type"); //get the cell from collection and info about cell

                if(type.equals("l") || type.equals("k")){
                    String color = cell.getChildText("color");
                    System.out.println(color);
                    char[] colorCharArray = color.toCharArray();
                    colorChar = colorCharArray[0];
                }else{
                    colorChar = 'q';
                }
                type = type + colorChar;
                cells.put(new Point(x, y), type);
            }

        } catch (JDOMException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return cells;
    }

    /**
     * Make the 2d tile array from the map of points to strings
     * @param map The map generated by makeMap. Map is of points to strings, each entry representing a tile
     * @return 2d Tile array of parsed XML representing the game
     */
    public Tile[][] makeTiles(Map<Point, String> map){
        Tile[][] cells = new Tile[mapSize][mapSize];
        for(Map.Entry<Point, String> entry : map.entrySet()){
            Point point = entry.getKey();
            String string = entry.getValue();
            char[] charArr = string.toCharArray();
            char type = charArr[0];
            char col = charArr[1];

            Tile tile = getTileFromChar(type, col);

            int x = point.x;
            int y = point.y;
            tile.setLocation(new Location(x, y));
            cells[y][x] = tile;
        }
        return cells;
    }

    /**
     *
     * @param c Character (each representing a different type of tile) to be parsed into a tile object
     * @param col Character representing the colour of the tile if it is a coloured tile
     * @return The tile object containing the character and colour information
     */
    public Tile getTileFromChar(Character c, Character col){
        String color = Character.toString(col);
        Tile tile = new Chap();
        if(c.equals('w')){
            tile = new WallTile();
        }else if(c.equals('f')){
            tile = new FreeTile();
        }else if(c.equals('k')){
            tile = new Key(color);
        }else if(c.equals('l')){
            tile = new Door(color);
        }else if(c.equals('i')){
            tile = new InfoField(LEVEL1INFO);
        }else if(c.equals('t')){
            tile = new Treasure();
        }else if(c.equals('q')){
            tile = new ExitLock();
        }else if(c.equals('e')){
            tile = new ExitTile();
        }else if(c.equals('c')){
            tile = new Chap();
        }else if(c.equals('a')){
            tile = new Actor();
        }
        return tile;
    }

    /**
     * Print tiles to console (system output)
     * @param tiles 2d Tile array of the board
     */
    public static void printTiles(Tile[][] tiles){
        for(int i = 0; i < mapSize; i++){
            for(int j = 0; j < mapSize; j++){
                Tile tile = tiles[i][j];
                String tileString = tile.toString();
                char[] tileCharArr = tileString.toCharArray();
                System.out.print(tileCharArr[0] + " ");
            }
            System.out.println();
        }
    }

    /**
     * get the 2d tile array represented as a string. Mostly for testing and assertion purposes.
     * @param tiles The 2d tile array to be turned into a string
     * @return String representing tile array
     */
    public static String getBoardString(Tile[][] tiles){
        StringBuilder sb = new StringBuilder();
        for(int i = 0; i < mapSize; i++){
            for(int j = 0; j < mapSize; j++){
                Tile tile = tiles[i][j];
                String tileString = tile.toString();
                char[] tileCharArr = tileString.toCharArray();
                sb.append(tileCharArr[0] + " ");
            }
            sb.append("\n");
        }
        return sb.toString();
    }
}
